DROP DATABASE IF EXISTS 20231164010027_CONSULTORIA;
CREATE DATABASE 20231164010027_CONSULTORIA;
USE 20231164010027_CONSULTORIA;

CREATE TABLE PACIENTE (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOME VARCHAR(150) NOT NULL,
CPF CHAR(14) NOT NULL,
DOENÇA VARCHAR(50)
);

CREATE TABLE MEDICO (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOME VARCHAR(150) NOT NULL,
MATRICULA INT NOT NULL,
ESPECIALIDADE VARCHAR(50) NOT NULL,
SALARIO DECIMAL(6,2)
);

CREATE TABLE PERMISSAO (
ID_MEDICO INT NOT NULL,
ID_PACIENTE INT NOT NULL,
HORARIO DATETIME,
PRIMARY KEY (ID_MEDICO, ID_PACIENTE),
FOREIGN KEY (id_medico) REFERENCES medico(id_medico)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
FOREIGN KEY (id_paciente) REFERENCES paciente(id_paciente)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);